const aiRes = [
  "The Notebook",
  " Titanic",
  " When Harry Met Sally",
  " Love Actually",
  "  Casablanca",
  "  Gone with the Wind",
  "  Sleepless in Seattle",
  "  Pretty Woman",
  "  Dirty Dancing",
  "  La La Land \n",
];

const tmdbRes = [
  [
    {
      adult: false,
      backdrop_path: "/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg",
      genre_ids: [10749, 18],
      id: 11036,
      original_language: "en",
      original_title: "The Notebook",
      overview:
        "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's. From a faded notebook, the old man's words bring to life the story about a couple who is separated by World War II, and is then passionately reunited, seven years later, after they have taken different paths.",
      popularity: 97.262,
      poster_path: "/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
      release_date: "2004-06-25",
      title: "The Notebook",
      video: false,
      vote_average: 7.889,
      vote_count: 11226,
    },
    {
      adult: false,
      backdrop_path: "/2CDjgYpwlRJeQnhycTkORzxrV7t.jpg",
      genre_ids: [18, 10752],
      id: 199615,
      original_language: "hu",
      original_title: "A Nagy Füzet",
      overview:
        "In a village on the Hungarian border, two young brothers grow up during war time with their cruel grandmother and must learn every trick of evil to survive in the absurd world of adults.",
      popularity: 17.243,
      poster_path: "/sUHTCB2mwaPhkwHUxGKp7OJ3M8s.jpg",
      release_date: "2013-07-03",
      title: "The Notebook",
      video: false,
      vote_average: 6.5,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/iMTod009PdlPAm6jP1Xb6I2LBwk.jpg",
      genre_ids: [99],
      id: 104901,
      original_language: "en",
      original_title: "From the Notebook of...",
      overview:
        "\"From the Notebook of...\" was shot in Florence and takes as its point of departure Leonardo da Vinci's notebooks and Paul Valéry's essay on da Vinci's process. These two elements suggest an implicit comparison between the treatment of space in Renaissance art and the moving image. The film marks a critical development in the artist's work in that he repeatedly employs a series of rapid pans and upward tilts along the city's buildings or facades, often integrating glimpses of his own face. As Beavers notes in his writing on the film, the camera movements are tied to the filmmakers' presence and suggests his investigative gaze.",
      popularity: 3.014,
      poster_path: "/liLwMNX9KSoY20Ooe8GVfvGKYMA.jpg",
      release_date: "1972-02-11",
      title: "From the Notebook of...",
      video: false,
      vote_average: 6,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 803974,
      original_language: "en",
      original_title: "The Notebooks",
      overview:
        "HE NOTEBOOKS is an inspiring film about friendship, love, and hope. When Preston Walker suddenly finds himself forgetting his memories, he puts a game plan in place to help him remember ...",
      popularity: 0.215,
      poster_path: "/3r5SOD3zaHjncSbHjpe2o4GjyL5.jpg",
      release_date: "2021-03-04",
      title: "The Notebooks",
      video: false,
      vote_average: 4,
      vote_count: 1,
    },
  ],
  [
    {
      adult: false,
      backdrop_path: "/sDH1LkdFOkQmTJaF1sIIniQyFOk.jpg",
      genre_ids: [18, 10749],
      id: 597,
      original_language: "en",
      original_title: "Titanic",
      overview:
        "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
      popularity: 159.098,
      poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      release_date: "1997-11-18",
      title: "Titanic",
      video: false,
      vote_average: 7.906,
      vote_count: 24830,
    },
    {
      adult: false,
      backdrop_path: "/2ZCq1wZ7avejS9Lkl0LmVpbiPec.jpg",
      genre_ids: [18, 10749, 53],
      id: 716855,
      original_language: "fi",
      original_title: "Sokea mies joka ei halunnut nähdä Titanicia",
      overview:
        "Jaakko and Sirpa have never met face to face, but talk on the phone every day. When Jaakko hears news about Sirpa's declining health, he decides to go meet her in another city. It's not the easiest decision, because he's blind and paralyzed from the chest down  - and he has to make the journey alone. To get there, Jaakko must rely on the help of five strangers. What could go wrong?",
      popularity: 22.59,
      poster_path: "/lYuZ8yvVuUJsISKY75yt6FIzJFb.jpg",
      release_date: "2021-09-10",
      title: "The Blind Man Who Did Not Want to See Titanic",
      video: false,
      vote_average: 7.186,
      vote_count: 35,
    },
  ],
  [
    {
      adult: false,
      backdrop_path: "/dbdegCWeD4iK5LXxSBjGdIRsVXS.jpg",
      genre_ids: [35, 10749, 18],
      id: 639,
      original_language: "en",
      original_title: "When Harry Met Sally...",
      overview:
        "During their travel from Chicago to New York, Harry and Sally debate whether or not sex ruins a friendship between a man and a woman. Eleven years later, and they're still no closer to finding the answer.",
      popularity: 32.464,
      poster_path: "/3wkbKeowUp1Zpkw1KkBqMWbt0P9.jpg",
      release_date: "1989-07-21",
      title: "When Harry Met Sally...",
      video: false,
      vote_average: 7.41,
      vote_count: 3975,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 27],
      id: 296273,
      original_language: "en",
      original_title:
        "When Harry Met Sally 2 with Billy Crystal and Helen Mirren",
      overview:
        "Billy proposes to producers a sequel with (literally) a bite to his classic movie.",
      popularity: 5.025,
      poster_path: "/5B2JBICP0acdv6ZdlLZo3QYQJbH.jpg",
      release_date: "2011-04-06",
      title: "When Harry Met Sally 2 with Billy Crystal and Helen Mirren",
      video: false,
      vote_average: 6.6,
      vote_count: 7,
    },
  ],
  [
    {
      adult: false,
      backdrop_path: "/xUWf5xX0AnZgAnYXAMk03zTbsef.jpg",
      genre_ids: [35, 10749, 18],
      id: 508,
      original_language: "en",
      original_title: "Love Actually",
      overview:
        "Eight London couples try to deal with their relationships in different ways. Their tryst with love makes them discover how complicated relationships can be.",
      popularity: 37.94,
      poster_path: "/1ODdWLpyOnIVl0l67GrdaFDlJGf.jpg",
      release_date: "2003-09-07",
      title: "Love Actually",
      video: false,
      vote_average: 7.116,
      vote_count: 6508,
    },
    {
      adult: false,
      backdrop_path: "/egvU7CBJqmzmk8OJgT11fP6mvdr.jpg",
      genre_ids: [18],
      id: 116005,
      original_language: "cn",
      original_title: "愛很爛",
      overview:
        "It tells a variety of stories about love that has gone wrong: a brother and sister in an illicit relationship, a married painter who falls in love with his young male life model, a dance school teacher who is besotted with his senior student, and a lesbian couple, one of whom has role-play paranoia, and is caught in a complex love triangle.",
      popularity: 25.03,
      poster_path: "/rg6nvLdz3Zt0ptBxHN9I9zBtd7C.jpg",
      release_date: "2012-03-29",
      title: "Love Actually... Sucks!",
      video: false,
      vote_average: 4.5,
      vote_count: 19,
    },
  ],
];

console.log(tmdbRes.flat(),"")